### ISSUE TITLE
CheckAllowedAdGroups not working

### ISSUE THREAD

**Issue by Vafele** [unosquare/passcore#182]
Hi,
We tried testing CheckAllowedAdGroups parameter in our environment, but didn't manage to get it to work. 
For example: 

"CheckRestrictedAdGroups": false,
    "RestrictedADGroups": ["Domain Users"
    ],
    "CheckAllowedAdGroups": true,
    "AllowedADGroups": [
"Domain Users"
]
  },

This does not work for domain users - I'm still getting the "You are not allowed to change your password" message.

On the other hand, if I set both Restricted and Allowed parameters to false, everything works fine. Same when testing with just "CheckRestrictedAdGroups": true  - the restriction is correctly applied to the groups set in the parameter.

**Comment by owls42** [comment]
I have this same issue - there is a logic problem in Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs (currently lines 73-82) where password change is denied if any single group a user is a member of is _not_ listed (it has been copy-pasted from the CheckRestrictedAdGroups block just above it)

**Comment by geoperez** [comment]
We change that logic, can you check the branch PassCore 3.5?

**Comment by geoperez** [comment]
Status?

**Comment by owls42** [comment]
I haven't installed that branch, but inspecting the code (in PasswordChangeProvider.cs, in the new / refactored function ValidateGroups) reveals it performs exactly the same logic test as before, so I strongly doubt that particular code will behave differently...

**Old** (Buggy code raises ChangeNotPermitted if the user is in _any_ _un_listed group)
`if (_options.CheckAllowedAdGroups)
                    {
                        foreach (var userPrincipalAuthGroup in userPrincipal.GetAuthorizationGroups())
                        {
                            if (!_options.AllowedADGroups.Contains(userPrincipalAuthGroup.Name))
                            {
                                return new ApiErrorItem { ErrorCode = ApiErrorCode.ChangeNotPermitted };
                            }
                        }
                    }`
**New**
`             if (options.AllowedADGroups?.Any() != true) return;
             foreach (var userPrincipalAuthGroup in userPrincipal.GetAuthorizationGroups())
            {
                if (!options.AllowedADGroups.Contains(userPrincipalAuthGroup.Name))
                {
                    throw new ApiErrorException("The User principal is not listed as allowed",
                        ApiErrorCode.ChangeNotPermitted);
                }
            }`

**Comment by geoperez** [comment]
I can't see the issue. Can you elaborate?

**Comment by owls42** [comment]
Sure.
Our AD users are members of a fairly wide range of security groups, which we use to assign permission to do various things on our infrastructure (e.g. write permission in a network folder, receive certain role-based notifications, etc)

The current logic in ValidateGroups (and the old logic) correctly blocks users from changing password if they are a member of _any_ group listed in RestrictedADGroups. However, it also blocks them from changing password, if _any group they are a member of_ is **not** listed in AllowedADGroups.

We find it completely infeasible to list all possible groups that a user may be a member of, in order to make use of the current code.

It needs to change to iterating over the AllowedADGroups list, and if a list constructed from userPrincipal.GetAuthorizationGroups() contains any one (or more) of the AllowedADGroups, the password is allowed to be changed.

**Comment by geoperez** [comment]
Let me add some unit test to verify the behavior.

**Comment by geoperez** [comment]
Hi @owls42 can you check the following file:
https://github.com/unosquare/passcore/blob/9e1b689b004d7bdd18a7283e16dd64f050f256fb/src/Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs#L140

**Comment by geoperez** [comment]
Please check the new version:

https://github.com/unosquare/passcore/releases/download/3.6.0/PassCore36.zip

**Comment by owls42** [comment]
Yes. the 3.6.0 release resolves this issue.
