### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by pduthieau** [unosquare/passcore#5]
Hi,

I'm getting this error when I attempt to change a password.

I'm also after some more information about how the application actually does the password change please - what permissions are required, etc?

**Comment by mariodivece** [comment]
The password change is done via Directory Services. The code can be found here:
https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs#L82

As far as the exception goes, my guess is that you are running the App pool under a user without proper permissions. Check this post out:
http://stackoverflow.com/questions/7901921/active-directory-exception-has-been-thrown-by-the-target-of-an-invocation

**Comment by pduthieau** [comment]
So by permissions do you mean an account that has permissions to reset the password? I changed both the website and the app pool to run as both a user with this permission, as well as trying the domain administrator account with no luck on either.

Should the Website be using the created Application Pool as it's App Pool, or should it use it's own?

**Comment by pduthieau** [comment]
How is the best way to display a more detailed error message?

**Comment by mariodivece** [comment]
To your first question, I don't really know. I only suggested the articles there because the error message typically appears because of some permission issue or when impersonation is not enabled.
To your second question, the error messages are fairly generic and meant for end users only. If you want exception details to troubleshoot your installations you will need to debug the application using Visual Studio 2015.

**Comment by mariodivece** [comment]
No response for this one in more than 2 weeks. Closing.
