### ISSUE TITLE
Upgrading from 2.0.2 Beta 2 to 4.2.4

### ISSUE THREAD

**Issue by emike09** [unosquare/passcore#617]
Hi all,
I just took over network administration for a new company and need to upgrade our Passcore from 2.0.2 Beta to the latest version. Browsing through the releases, I noticed the application structure changed dramatically from 2.0.2 to 3.0. 

I've attempted to update by following the standard installation instructions, but that simply breaks the site. "Loading Passcore" flashes, then a blank page with a title of 'undefined'. I'm not an IIS expert by any means, and wondering if I'm missing something on that side. Honestly' I'm not really sure where to start. VM is running Server 2012 R2. 

Any tips?

**Describe the solution you'd like**
Upgrade from 2.0.2 Beta 2 to 4.2.4

**Describe alternatives you've considered**
Building a new VM from scratch.

**Comment by sergiochoo** [comment]
@emike09 I found this software 3 month ago.
Since then I've attempted to install this as a docker container and then on IIS. Both - no luck.
The web-form is appearing, but changing password doesn't happen. 00000 unknown error.
You should stay on 2.0.2 Beta, because it works as opposed to the latest version.
I guess, last versions of Passcore were broken on purpose, because developer suggest "PRO" version "for only" $49.99/year :)
So sorry.

**Comment by unquietwiki** [comment]
@emike09 @sergiochoo Your best bet is to take the old appsettings.json; set that aside; then fill in the newer version with appropriate settings from your old one. I don't think these guys broke it on purpose: I was using this stuff 3 years ago (helped put the DefaultDomain feature to use), and they just gladly accepted a code-change from me yesterday to fix up some stuff.
